---
title: "ENU R Workshop - presentation slides"
author: "Michelle Jamieson & Jan Savinc"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Contents/outline/TODO list

## Long list of contents

The presentation should cover the following:

-   installing/loading packages
    -   session, environment, restarting session
-   setting up project & folder
    -   absolute vs relative path
    -   project skeleton
-   read in excel file
    -   excel_sheets()
    -   read_excel()
-   data.frames/tibbles
    -   what they are
    -   accessing values/rows/columns/indexing
    -   saving as .csv/.xlsx (openxlsx::write.xlsx)
-   cleaning
    -   janitor::clean_names()
    -   various ways of renaming data
    -   naming conventions
    -   checking data
        -   summary, glimpse(), skimr::skim(), range()
        -   count(is.na(x)), count()
    -   converting to NA - if_else(), replace()
    -   recoding - replace some values with others
    -   type conversions
    -   working with dates, lubridate
-   descriptive stats: means, sd, median
    -   group_by()
    -   summarise()
-   ggplot()
    -   grammar of graphics intro: data + layers/geoms/aesthetics
    -   histogram, bar chart, line chart, box plots
    -   faceting
    -   adding summary statistics by computing them as a separate table
    -   best practice for displaying categorical vs numerical data
    -   colour/linetype/size
    -   ggsave(), formats, png, pdf, svg, resolution, size of plot, aspect ratio

Reference for slides (ioslides): <https://bookdown.org/yihui/rmarkdown/ioslides-presentation.html>

# Seting up project & folders

## Start new project in R

-   File - New Project

TODO: include a screenshot of the New Project window!

## File paths: absolute vs. relative

-   Absolute paths specify the full 'address' of a file
    -   e.g. "C:/Users/123456/OneDrive - Edinburgh Napier University/training/WORKBOOK.xlsx"
    -   Helpful in some scenarios, e.g. when the data cannot be inside the project folder
-   Relative paths specify the address relative to a 'working directory'
    -   e.g. "./data/raw/WORKBOOK.xlsx"
    -   the dot ('.') means 'working directory'
    -   when using R projects, the working directory is the project folder
    -   two dots ('..') means 'move one directory up' - e.g. "../other project folder/data/raw_data.csv"

# Data frames/tibbles

## What are data frames/tibbles?

-   Data frames (or tibbles, in tidyverse) are like spreadsheets in R
-   Rectangular structure: rows X columns
-   Each column has a *type*:
    -   character (any text you like!)
    -   integer (integers, 0,1,2,3,...)
    -   numeric (e.g. decimal numbers)
    -   logical (TRUE/FALSE)

## Addressing / indexing values in data frames

-   Each entry in a data frame/tibble has an 'address' - its position in terms of rows and columns
-   You can refer to values in a data frame using an index in rectangular brackets:
    -   df[3,5] refers to the value in data frame *df* at row 3 and column 5
-   Columns have names, so you can also refer to a named column:
    -   df[2, "smoking status"] refers to 2nd row, column "smoking status"
    
## Addressing / indexing values in data frames
    
-   Special case: you can leave out the row or column position, and it will get all rows or all columns
    -   df[6,] refers to row 6 and all columns
    -   df[,9] refers to all rows and column 9
    -   df[, ] refers to all of df (the same as calling df directly!)

## Dollar sign notation (\$)

-   You can also refer to a column using the dollar sign ('$'): - df$postcode refers to the 'postcode' column - note there's no quotes around the name in this case!

## Functions on data frames

-   running just the name of the data frame/tibble, e.g. `df` is the same as running `print(df)` and will show you the first 10 rows of the data
-   `summary(df)` runs some very basic descriptive statistics on all the columns
-   `glimpse(df)` (part of the *tidyverse* package) shows you all the columns and lists the first few values for each column

## Saving data frames as files

-   To save a data frame as a file, you can use the following:
    -   `write_csv(df,  file = "path_to_file.csv")` saves the data frame as a .csv file
    -   `openxlsx::write.xlsx(df, "path_to_file.xlsx")` saves the data frame as an excel (.xlsx) file
    
    
# Reading excel files

## Reading excel files

- Excel files can have multiple sheets/tabs
- `{readxl}` package for reading excel files
- `excel_sheets()` shows you the names of the sheets/tabs
- `read_excel()` will read a specific sheet/tab from an excel file (you need to specify the name or the number of the sheet!)
  - e.g. `read_excel(path = "my_excel_file.xlsx", sheet = 2)` will read the 2nd tab in the file
- Read specific cell range in sheet: `read_excel(path = "my_excel_file.xlsx", sheet = 2, range = "A5:G24")`
